CREATE TABLE USUARIO(
LOGIN VARCHAR2(20 BYTE) PRIMARY KEY,
PASSWORD NVARCHAR2(100),
NOMBRE VARCHAR2(50 BYTE),
CLIENTE FLOAT,
EMAIL VARCHAR2(50 BYTE),
FECHA_ALTA DATE,  --SYSDATE
FECHA_BAJA DATE,
STATUS CHAR(1 BYTE), --A
INTENTOS FLOAT,
FECHA_REVOCADO DATE,
FECHA_VIGENCIA DATE,
NO_ACCESO INTEGER,
APELLIDO_PATERNO VARCHAR2(50 BYTE),
APELLIDO_MATERNO VARCHAR2(50 BYTE),
--AREA NUMBER(4),
FECHA_MODIFICACION DATE --SYSDATE
);

SELECT * FROM USUARIO;

DROP TABLE USUARIO;

INSERT INTO USUARIO VALUES('Sara12','sara123','Sara',1.3,'sara@gmail.com',SYSDATE,'02/09/2023','A',0,'03/09/2023','04/09/2023',1,'Veliz','Severiano',1,SYSDATE);

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

COMMIT;